### ISSUE TITLE
Debian dependences

### ISSUE THREAD

**Issue by fabitom** [DanielOliveiraSouza/LAMW4Linux-installer#13]
Installer stoped with:
svn: command not found
and
git: command not found

Please add git and subversion dependences.

**Comment by DanielOliveiraSouza** [comment]
This dependencies already to mark to install ( file lamw_manager/core/lamw_headers line 152 )
Check your  /etc/apt/sources.list  add contrib non-free repository 
Check the key  of repository
Run **apt-get update** to descover origin of error.
Run apt show subversion | grep Sources to discover URL package download
Run apt show git | grep Source to discover URL Package download
If this commands fault, then exists a problem in /etc/apt/sources.list  
If you are not know how to edit /etc/apt/source.list  go to [https://debgen.simplylinux.ch/]

**Comment by DanielOliveiraSouza** [comment]
My /etc/apt/sources.list
#Fonte de aplicativos apt
deb http://ftp.br.debian.org/debian/ buster main **contrib non-free**
deb-src http://ftp.br.debian.org/debian/ buster **main contrib non-free**

deb http://security.debian.org/ buster/updates **main contrib non-free**
deb-src http://security.debian.org/ buster/updates **main contrib non-free**

# buster-updates, previously known as 'volatile'
deb http://ftp.br.debian.org/debian/ buster-updates **main contrib non-free**
deb-src http://ftp.us.debian.org/debian/ buster-updates **main contrib non-free**

#Adiciona fontes extras ao debian
# debian backports
deb http://ftp.debian.org/debian buster-backports **main contrib non-free**
deb-src http://ftp.debian.org/debian buster-backports **main contrib non-free**
#Adiciona suporte ao wine
deb https://dl.winehq.org/wine-builds/debian/ buster main
deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main

**Comment by fabitom** [comment]
Ok, that was new fresh vbox installation of debian 10 x64. I installed manually.
My default sources.list:
deb http://ftp.task.gda.pl/debian/ buster main
deb-src http://ftp.task.gda.pl/debian/ buster main

deb http://security.debian.org/debian-security buster/updates main
deb-src http://security.debian.org/debian-security buster/updates main

deb http://ftp.task.gda.pl/debian/ buster-updates main
deb-src http://ftp.task.gda.pl/debian/ buster-updates main

**Comment by DanielOliveiraSouza** [comment]
Debian by default have in your official repository (**main**) only softwares free (opensource) 
Read more in **https://wiki.debian.org/DFSGLicenses**.
Property softwares can installed from repository **non-free**
Softwares free with depends of property can installed from **contrib**

I will add a specific documentation to Debian
Thanks, good lock!

**Comment by DanielOliveiraSouza** [comment]
Install dependencies was divided in two parts, part free and non-free.
And the was added especifics  docs for  debian
